# Generated by Django 4.2.11 on 2024-08-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedido_cep_remove_pedido_cidade_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ('cliente', 'indice'), 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AddField(
            model_name='pedido',
            name='indice',
            field=models.IntegerField(default=0),
        ),
    ]
